// constants/dietaryCategories.js
export const ALLOWED_CATEGORIES = [
    "Biryani Varieties",
    "Nihari Delicacies",
    "Karahi Creations",
    "Korma Specialties",
    "Haleem Masterpieces",
    "Kebab Assortments",
    "Tandoori Treats",
    "Curry Classics",
    "Pulao Dishes",
    "Daal Delights",
    "Chaat Sensations",
    "Paratha Varieties",
    "Naan & Flatbreads",
    "Samosa Selections",
    "Pakora & Bhaji",
    "Pickles & Chutneys",
    "Raita & Yogurt Dishes",
    "Saag & Green Vegetable Curries",
    "Vegetable Curries",
    "Mughlai Influences",
    "Street Food Specialties",
    "Seafood Selections",
    "Traditional Desserts",
    "Rice Puddings & Kheer",
    "Sheer Khurma",
    "Lassi & Yogurt Drinks",
    "Chai Varieties",
    "Halwa Creations",
    "Salad & Raita Innovations",
    "Fusion Desi Snacks"
  ];
   